splash = false
ipc = on

wallpaper {
    monitor = DP-1
    path = /home/major/Pictures/wallpaper/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/major/Pictures/wallpaper/wallpaper.jpg
    fit_mode = cover
}
